package ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Table(name = "OocpaApplication")
public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPLICATION_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "APPLICATION_ID_GENERATOR", sequenceName = "APPLICATION_ID_SEQ")
	private java.lang.Long id;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Patient patient;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Provider provider;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.ValidationMessage> validationResults;

	private java.lang.String priority;

	private java.util.Date receivedDate;

	private java.lang.String PANumber;

	private java.lang.String serviceCategory;

	private java.util.Date scheduledAdmissionDate;

	private java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.File> files;

	public Application() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Patient getPatient() {
		return this.patient;
	}

	public void setPatient(
			ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Patient patient) {
		this.patient = patient;
	}

	public ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Provider getProvider() {
		return this.provider;
	}

	public void setProvider(
			ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Provider provider) {
		this.provider = provider;
	}

	public java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.ValidationMessage> getValidationResults() {
		return this.validationResults;
	}

	public void setValidationResults(
			java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.ValidationMessage> validationResults) {
		this.validationResults = validationResults;
	}

	public String toString() {
		return "Application: id=" + this.id + ",patient=" + this.patient
				+ ", provider=" + this.provider;
	}

	public java.lang.String getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.String priority) {
		this.priority = priority;
	}

	public java.util.Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(java.util.Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	public java.lang.String getPANumber() {
		return this.PANumber;
	}

	public void setPANumber(java.lang.String PANumber) {
		this.PANumber = PANumber;
	}

	public java.lang.String getServiceCategory() {
		return this.serviceCategory;
	}

	public void setServiceCategory(java.lang.String serviceCategory) {
		this.serviceCategory = serviceCategory;
	}

	public java.util.Date getScheduledAdmissionDate() {
		return this.scheduledAdmissionDate;
	}

	public void setScheduledAdmissionDate(java.util.Date scheduledAdmissionDate) {
		this.scheduledAdmissionDate = scheduledAdmissionDate;
	}

	public java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.File> getFiles() {
		return this.files;
	}

	public void setFiles(
			java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.File> files) {
		this.files = files;
	}

	public Application(
			java.lang.Long id,
			ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Patient patient,
			ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Provider provider,
			java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.ValidationMessage> validationResults,
			java.lang.String priority,
			java.util.Date receivedDate,
			java.lang.String PANumber,
			java.lang.String serviceCategory,
			java.util.Date scheduledAdmissionDate,
			java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.File> files) {
		this.id = id;
		this.patient = patient;
		this.provider = provider;
		this.validationResults = validationResults;
		this.priority = priority;
		this.receivedDate = receivedDate;
		this.PANumber = PANumber;
		this.serviceCategory = serviceCategory;
		this.scheduledAdmissionDate = scheduledAdmissionDate;
		this.files = files;
	}
}