package ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Table(name = "OocpaApplication")
public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "APPLICATION_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "APPLICATION_ID_GENERATOR", sequenceName = "APPLICATION_ID_SEQ")
	private java.lang.Long id;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Patient patient;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Provider provider;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.ValidationMessage> validationResults;

	public Application() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Patient getPatient() {
		return this.patient;
	}

	public void setPatient(
			ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Patient patient) {
		this.patient = patient;
	}

	public ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Provider getProvider() {
		return this.provider;
	}

	public void setProvider(
			ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Provider provider) {
		this.provider = provider;
	}

	public java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.ValidationMessage> getValidationResults() {
		return this.validationResults;
	}

	public void setValidationResults(
			java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.ValidationMessage> validationResults) {
		this.validationResults = validationResults;
	}

	public Application(
			java.lang.Long id,
			ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Patient patient,
			ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.Provider provider,
			java.util.List<ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication.ValidationMessage> validationResults) {
		this.id = id;
		this.patient = patient;
		this.provider = provider;
		this.validationResults = validationResults;
	}

}