package ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class File implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.Id
	private java.lang.Long id;

	private java.lang.String fileName;

	private java.lang.String fileType;

	private java.lang.Integer fileSizeKb;

	private java.lang.String fileLink;

	public File() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFileName() {
		return this.fileName;
	}

	public void setFileName(java.lang.String fileName) {
		this.fileName = fileName;
	}

	public java.lang.String getFileType() {
		return this.fileType;
	}

	public void setFileType(java.lang.String fileType) {
		this.fileType = fileType;
	}

	public java.lang.Integer getFileSizeKb() {
		return this.fileSizeKb;
	}

	public void setFileSizeKb(java.lang.Integer fileSizeKb) {
		this.fileSizeKb = fileSizeKb;
	}

	public java.lang.String getFileLink() {
		return this.fileLink;
	}

	public void setFileLink(java.lang.String fileLink) {
		this.fileLink = fileLink;
	}

	public File(java.lang.Long id, java.lang.String fileName,
			java.lang.String fileType, java.lang.Integer fileSizeKb,
			java.lang.String fileLink) {
		this.id = id;
		this.fileName = fileName;
		this.fileType = fileType;
		this.fileSizeKb = fileSizeKb;
		this.fileLink = fileLink;
	}

}