package ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Table(name = "OocpaPatient")
public class Patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "PATIENT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PATIENT_ID_GENERATOR", sequenceName = "PATIENT_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String firstName;

	private java.lang.String lastName;

	private java.lang.Long healthNum;

	public Patient() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.Long getHealthNum() {
		return this.healthNum;
	}

	public void setHealthNum(java.lang.Long healthNum) {
		this.healthNum = healthNum;
	}

	public Patient(java.lang.Long id, java.lang.String firstName,
			java.lang.String lastName, java.lang.Long healthNum) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.healthNum = healthNum;
	}
	
	public String toString(){
	  return "Patient: id=" + this.id + ", healthNum=" + this.healthNum + ", firstName=" + this.firstName + ", lastName=" + this.lastName;   
	}

}