package ca.ontario.health.hsc.prsb.oocpa.oocpa_validatenewapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Table(name = "OocpaAppVldtnMsg")
public class ValidationMessage implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "VALIDATIONMESSAGE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "VALIDATIONMESSAGE_ID_GENERATOR", sequenceName = "VALIDATIONMESSAGE_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Description("domain: {Info, Warn, Error}")
	private java.lang.String type;

	private java.lang.String text;

	@org.kie.api.definition.type.Description("domain: {Patient, Provider}")
	private java.lang.String sourceType;

	public ValidationMessage() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getText() {
		return this.text;
	}

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(java.lang.String sourceType) {
		this.sourceType = sourceType;
	}

	public ValidationMessage(java.lang.Long id, java.lang.String type,
			java.lang.String text, java.lang.String sourceType) {
		this.id = id;
		this.type = type;
		this.text = text;
		this.sourceType = sourceType;
	}

}